version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - 8wekyb3d8bbwe
  - cw5n1h2txyewy
  - Dism
  - fjemmk5ta3a5g
  - HarddiskVolume
  - Wusa
  - IE4UINIT
ignoreWords: []
import: []
